# Generated by Django 2.0.4 on 2018-04-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='date_end',
        ),
        migrations.RemoveField(
            model_name='price',
            name='date_start',
        ),
        migrations.AddField(
            model_name='price',
            name='day_end',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='price',
            name='day_start',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='price',
            name='month_end',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='price',
            name='month_start',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='price',
            name='year_end',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='price',
            name='year_start',
            field=models.IntegerField(default=-1),
        ),
    ]
