# Generated by Django 2.0.4 on 2018-04-25 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0001_initial'),
        ('price', '0002_auto_20180424_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='supermarket',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='supermarket.Supermarket'),
        ),
    ]
