# Generated by Django 2.0.4 on 2018-04-28 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0004_auto_20180428_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='product.Product'),
        ),
        migrations.AlterField(
            model_name='price',
            name='supermarket',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='supermarket.Supermarket'),
        ),
    ]
