# Generated by Django 2.0.4 on 2018-04-25 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20180425_0635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='supermarket',
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
