# Generated by Django 2.0.5 on 2018-05-07 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20180425_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(default='', height_field=240, upload_to='thumbnails/', width_field=240),
        ),
    ]
